### ISSUE TITLE
Validation: equipartition of energy w/o forcing and nonlinear contributions

### ISSUE THREAD

**Issue by ryo-ARAKI** [ryo-ARAKI/Sabra_shell_model#24]
- Check energy equipartition without forcing
- Other points to check?

**Comment by ryo-ARAKI** [comment]
@T-Tanogami These validation works are indeed great! Thank you for your effort (It should have been painful to handle all these modifications). For small \epsilon, I realised the problem (with bugged code). I still do not 100% understand the exact procedure in Eyink, et al. paper. What did they implement in the simulation code and what did they do in the post-processing???

**Comment by T-Tanogami** [comment]
Such a small \epsilon is probably caused by either a short simulation or a bug.

Now, I explain the procedure of the paper.
We first note that, in order for the 0-th shell to correspond exactly with the Kolmogorov scale, \epsilon must be 1 (since k_n is now non-dimensionalized by the Kolmogorov scale \eta=\nu^{3/4}\epsilon^{-1/4} with \nu=1).
However, with deterministic external forces, it is difficult to precisely set \epsilon=1 (BTW, if we use the random forcing, the injection (dissipation) rate is under control).
Therefore, Eyink et al. try to set \epsilon=1 as follows.
First, they guessed at an appropriate parameter value (\theta_K=2.83*10^-8, Re~10^7) and obtained \epsilon=1.478.
Then, to set \epsilon=1, they rescale all the variables by \epsilon=1.478.
After this rescaling, \epsilon=1, u_rms=56.48, Re=u_rms/\nu*k_M=56.48/(1.0*2^{-15}*(1.478)^{-1/4})=2.04*10^6, and \theta_K=2.83*10^-8/(1.478)^0.5=2.328*10^-8.
Note that we do not have to do these steps if we use the above parameter values that they obtained.

**Comment by ryo-ARAKI** [comment]
@T-Tanogami Your comment makes it clear how they "assume" parameters first and rescale all quantities by epsilon.
We now have unrescaled \epsilon while we implement rescaled \theta_K and Re as the parameters. OK, that sure will be a problem.

**Comment by T-Tanogami** [comment]
@ryo-ARAKI 
![time_average_psd_n=-02_07_thetaK=2 328e-08_Re=2 040e+06_itr=11E7_to_110E7_ens=1](https://user-images.githubusercontent.com/92904878/142849324-5e860853-1e91-4abc-8fbf-6d0249ad4b8a.png)
I did a simulation for B_n=f_n=0 with M=-2 more carefully. This figure shows \epsilon_n:=<|u_n|^2>/2. In this simulation, I took the time average over 100 different times at t=1000+100*i (i=1,2,...,100). (In this case, the largest time scale is the characteristic time scale for the viscous damping at shell M: t_M:=1/(k_M)^2=4<<100.) The solid line denotes \theta_K=2.328e-8. Although the relation \epsilon_n=\theta_K should hold for all n, it seems not satisfied. Why? Of course, the time average over 100 different times is not sufficient, and I also must take the ensemble average. However, this result suggests that there is something wrong with the code. Could you perform the numerical calculation for this case with more sufficient averaging?

Parameter values are: 
    M = -2
    R = 7
    k₀ = 1.0
    θK = 2.328e-8
    Re = 2.04e6
    Δt = 1.0e-5

**Comment by T-Tanogami** [comment]
@ryo-ARAKI Great. Thank you for checking this. I realized the importance of the ensemble average. Now, the next task is to check the Kolmogorov spectrum with the dissipation rate \epsilon=O(1).

**Comment by ryo-ARAKI** [comment]
OK. I will close this issue by changing the title. I will create a new issue with the Kolmogorov spectrum.

**Comment by ryo-ARAKI** [comment]
![spectrum_energy_average_only](https://user-images.githubusercontent.com/28855387/143410093-14292d81-fbbc-43dd-954c-de9e0426e4ee.png)

- Ensemble average over 100 sample at t=1000

![spectrum_energy_average](https://user-images.githubusercontent.com/28855387/143410522-f25d1a29-0acc-4f86-85d4-de9d5c02778a.png)

- Ensemble average with standard deviation and all data (I manually set yaxis lim so that not all data are visualised).

**Comment by T-Tanogami** [comment]
@ryo-ARAKI Thank you for your effort. It seems to work well.
